; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
;build_flags = 
;  -I $PROJECT_DIR/include

[env:nodemcu-32s-happy]
extends = env:nodemcu-32s
build_flags =
  -DEA_EXAMPLE_HAPPY_PATH

[env:nodemcu-32s-advanced]
extends = env:nodemcu-32s
build_flags =
  -DEA_EXAMPLE_ADVANCED_API
