[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env:nodemcu-32s-hello]
extends = env:nodemcu-32s
build_flags =
  -DEA_EXAMPLE_HELLO_WORLD
